version: '3'
services:
  frontend:
    depends_on: 
      - elastic
      - crawler
      - backend
    build:
      context: frontend/
      args:
        - REACT_APP_BACKEND_URL=http://localhost:4000
    ports: 
      - "80:80"   
  backend:
    environment:
      - PORT=4000
      - ELASTIC_SEARCH_URL=http://elastic:9200
    depends_on: 
      - elastic
      - crawler
    build:
      context: backend/
    ports: 
      - "4000:4000" 
  crawler:
    environment:
      - ELASTIC_SEARCH_URL=http://elastic:9200
      - NODE_ENV=production
    depends_on: 
      - elastic
    build:
      context: crawler/
  elastic:
    environment: 
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    # ports: 
      # - "9200:9200"
    volumes:
      - elastic_search_data:/usr/share/elasticsearch/data
volumes: 
  elastic_search_data:
    driver: local